import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { FlyToCartProvider } from "@/components/system components/store components/FlyToCartProvider";
import TanstackQueryProvider from "@/lib/tanstackQueryProvider";
import ToastProvider from "@/components/ToasterProvider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { UserProvider } from "@/lib/userContext";
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable}  ${montserrat.className}  antialiased`}
      >
        <TanstackQueryProvider>
          <FlyToCartProvider>
            <TooltipProvider>
              <UserProvider>{children} </UserProvider>
            </TooltipProvider>
          </FlyToCartProvider>
        </TanstackQueryProvider>

        <ToastProvider />
      </body>
    </html>
  );
}
