import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { FlyToCartProvider } from "@/components/system components/store components/FlyToCartProvider";
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable}  ${montserrat.className}  antialiased`}
      >
        <FlyToCartProvider>{children}</FlyToCartProvider>
      </body>
    </html>
  );
}
