export const students = [
  {
    id: 1,
    name: "Ryan Joel Castro",
    points: 120000,
    level: 289,
    rankLabel: "God Level",
    clan: "Dark Knights",
  },
  {
    id: 2,
    name: "Anna Jumfruit",
    points: 200922,
    level: 289,
    rankLabel: "God Level",
    clan: "Dark Knights",
  },
  {
    id: 3,
    name: "Mark Twain",
    points: 150987,
    level: 289,
    rankLabel: "God Level",
    clan: "Dark Knights",
  },
  {
    id: 4,
    name: "John Legend",
    points: 90876,
    level: 289,
    rankLabel: "God Level",
    clan: "Dark Knights",
  },

  // NEW 16 DATA 👇
  {
    id: 5,
    name: "Sophia Reyes",
    points: 180321,
    level: 250,
    rankLabel: "Master",
    clan: "Sky Warriors",
  },
  {
    id: 6,
    name: "Liam Santos",
    points: 132450,
    level: 210,
    rankLabel: "Elite",
    clan: "Shadow Clan",
  },
  {
    id: 7,
    name: "Noah Cruz",
    points: 175600,
    level: 240,
    rankLabel: "Master",
    clan: "Blaze Guild",
  },
  {
    id: 8,
    name: "Emma Garcia",
    points: 165890,
    level: 230,
    rankLabel: "Master",
    clan: "Sky Warriors",
  },
  {
    id: 9,
    name: "Lucas Mendoza",
    points: 110230,
    level: 200,
    rankLabel: "Elite",
    clan: "Dark Knights",
  },
  {
    id: 10,
    name: "Mia Torres",
    points: 140876,
    level: 215,
    rankLabel: "Elite",
    clan: "Blaze Guild",
  },
  {
    id: 11,
    name: "Ethan Villanueva",
    points: 190543,
    level: 260,
    rankLabel: "Grandmaster",
    clan: "Shadow Clan",
  },
  {
    id: 12,
    name: "Ava Ramirez",
    points: 170210,
    level: 235,
    rankLabel: "Master",
    clan: "Sky Warriors",
  },
  {
    id: 13,
    name: "James Bautista",
    points: 98000,
    level: 180,
    rankLabel: "Advanced",
    clan: "Dark Knights",
  },
  {
    id: 14,
    name: "Isabella Flores",
    points: 125600,
    level: 205,
    rankLabel: "Elite",
    clan: "Blaze Guild",
  },
  {
    id: 15,
    name: "Benjamin Navarro",
    points: 155340,
    level: 225,
    rankLabel: "Master",
    clan: "Shadow Clan",
  },
  {
    id: 16,
    name: "Charlotte Aquino",
    points: 167890,
    level: 238,
    rankLabel: "Master",
    clan: "Sky Warriors",
  },
  {
    id: 17,
    name: "Daniel Castillo",
    points: 102345,
    level: 195,
    rankLabel: "Advanced",
    clan: "Dark Knights",
  },
  {
    id: 18,
    name: "Amelia Delgado",
    points: 145678,
    level: 220,
    rankLabel: "Elite",
    clan: "Blaze Guild",
  },
  {
    id: 19,
    name: "Michael Herrera",
    points: 135999,
    level: 212,
    rankLabel: "Elite",
    clan: "Shadow Clan",
  },
  {
    id: 20,
    name: "Harper Salazar",
    points: 160450,
    level: 228,
    rankLabel: "Master",
    clan: "Sky Warriors",
  },
];
